### ISSUE TITLE
Failsafe problem

### ISSUE THREAD

**Issue by Mogway28** [MikeBland/SbusToPpm#5]
When FS on FRSKY then all chanell sets on min value instead of FS value. Probably is because there is SBUS signal but with no pulse . When signal pin is disconnected then FS values are proper.

Anyway  very usefull code.

**Comment by MikeBland** [comment]
I currently ignore the FS bit in the SBUS frame, but assume that if a FrSky Rx goes into failsafe, then it sends the failsafe values in the Rx out on the SBUS. In this state, the servo outputs should go to the values set in the Rx.

**Comment by Mogway28** [comment]
There is 3 option In Frsky system:
on (TX)-  NOT SET, NOPULSE, CUSTOM SET and F/S switch on RX.
F/S on RX seems to not sets chanel provided by  SBUS only for PWM output(?!!)
NOT SET -  when FS  all chanel sets to min(SBUS)
NOPULSE - when FS  all chanel sets to min(SBUS)
CUSTOM - only then it sets proper value on chanel via SBUS

When SBUS is connected  there is always sbus frame an RX sets rx chanel to minimum when FS ( beside CUSTOM set mode)
